export const TIME_DELAY = 1300;
export const COPY_WRITE = 'Copy'
export const PASTE_READ = 'Paste'
export const COPY_WRITE_INFO = 'write from textarea to clipboard'
export const PASTE_READ_INFO = 'read from clipboard'
export const COPY_WRITE_SET_TIMEOUT = `${COPY_WRITE} setTimeout`
export const PASTE_READ_SET_TIMEOUT = `${PASTE_READ} setTimeout`
export const PASTE_SUCCESS = `${PASTE_READ} success`
export const COPY_WRITE_SUCCESS = `${COPY_WRITE} success`